In [ ]:
##1
import numpy as np

In [ ]:
#2
np.__version__
np.show_config()

'1.26.4'

In [ ]:
#3
t=np.zeros(10)
print(t)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
#4
print('%d bytes'%(t.size * t.itemsize))

80 bytes


In [15]:
#6
r=np.zeros(10)
r[4]=1
print(r)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7 - vector with values ranging from 10 to 49
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [18]:
#8 - reverse a vector (first element becomes last)
trg=np.arange(15)
trg=trg[::-1]
print(trg)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [21]:
#9 - 3x3 matrix with values ranging from 0 to 8
yup=np.arange(9).reshape(3,3)
print(yup)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
#10 - Find indices of non-zero elements from [1,2,0,0,4,0]
ilt=[1,2,0,0,4,0]
lo=np.nonzero(ilt)
print(lo)

(array([0, 1, 4], dtype=int64),)


In [24]:
#11 - Create a 3x3 identity matrix
i3=np.eye(3)
print(i3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#12 - Create a 3x3x3 array with random values
rrand=np.random.random((3,3,3))
print(rrand)    

[[[0.5682381  0.90306136 0.08096804]
  [0.31110354 0.18935786 0.61880761]
  [0.77871841 0.51478544 0.61650103]]

 [[0.23931835 0.03691935 0.39027268]
  [0.23045443 0.85188483 0.6458845 ]
  [0.06279998 0.38673107 0.41409646]]

 [[0.72199208 0.19364657 0.16069929]
  [0.60083545 0.58432792 0.0261178 ]
  [0.56355844 0.47542091 0.9743684 ]]]


In [ ]:
#13 - 10x10 array with random values and find the minimum and maximum values
g= np.random.random((10,10))
gmax,gmin=g.max(),g.min()
print(gmax,gmin)

0.9972871826837384 0.0009424205578665301


In [28]:
#14 - Create a random vector of size 30 and find the mean value
f=np.random.random(30)
fmean=f.mean()
print(fmean)

0.5055872350382624


In [31]:
#15 - Create a 2d array with 1 on the border and 0 inside
h=np.ones((10,10))
h[1:-1,1:-1]=0
print(h)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
