In [2]:
##1
import numpy as np

In [3]:
#2
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/theop/anaconda3/Library/include
    lib directory: C:/Users/theop/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

In [4]:
#3
t=np.zeros(10)
print(t)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4
print('%d bytes'%(t.size * t.itemsize))

80 bytes


In [6]:
#6
r=np.zeros(10)
r[4]=1
print(r)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7 - vector with values ranging from 10 to 49
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#8 - reverse a vector (first element becomes last)
trg=np.arange(15)
trg=trg[::-1]
print(trg)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [9]:
#9 - 3x3 matrix with values ranging from 0 to 8
yup=np.arange(9).reshape(3,3)
print(yup)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10 - Find indices of non-zero elements from [1,2,0,0,4,0]
ilt=[1,2,0,0,4,0]
lo=np.nonzero(ilt)
print(lo)

(array([0, 1, 4], dtype=int64),)


In [11]:
#11 - Create a 3x3 identity matrix
i3=np.eye(3)
print(i3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12 - Create a 3x3x3 array with random values
rrand=np.random.random((3,3,3))
print(rrand)    

[[[0.21034726 0.58072518 0.74871694]
  [0.75133562 0.06738869 0.58312796]
  [0.65927808 0.72606774 0.26637444]]

 [[0.36271578 0.86983816 0.5190886 ]
  [0.4649289  0.32054974 0.21964871]
  [0.8184284  0.8976492  0.95227103]]

 [[0.72471314 0.41289028 0.85289019]
  [0.36979783 0.30852174 0.88381001]
  [0.54911309 0.78448687 0.42423427]]]


In [13]:
#13 - 10x10 array with random values and find the minimum and maximum values
g= np.random.random((10,10))
gmax,gmin=g.max(),g.min()
print(gmax,gmin)

0.9961240634980584 0.018631929490605215


In [14]:
#14 - Create a random vector of size 30 and find the mean value
f=np.random.random(30)
fmean=f.mean()
print(fmean)

0.4579655976753288


In [15]:
#15 - Create a 2d array with 1 on the border and 0 inside
h=np.ones((10,10))
h[1:-1,1:-1]=0
print(h)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# 16. add a border (filled with 5's) around an existing array
rrands=np.ones((5,5))
rrands=np.pad(rrands, pad_width=1, mode='constant', constant_values=5)
print(rrands)

[[5. 5. 5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]


In [18]:
#17
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
#18 - 5x5 matrix with values 1,2,3,4 just below the diagonal
dia=np.diag(1+np.arange(4),k=-1)
print(dia)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
#19 -  8x8 matrix and fill it with a checkerboard pattern
dfo=np.zeros((8,8),dtype=int)
dfo[1::2,::2] = 1
dfo[::2,1::2]=1
print(dfo)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
#20 -  a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [ ]:
#21 - a checkerboard 8x8 matrix using the tile function
v=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#22 - Normalize a 5x5 random matrix
v=np.random.random((5,5))
v=(v-np.mean(v))/(np.std(v))
print(v)

[[-7.95778592e-01  5.77512185e-01 -1.78777855e+00 -1.01089180e+00
  -5.24742509e-02]
 [ 3.10604392e-01 -8.46475777e-04  6.32678267e-01  5.31169935e-01
   1.31026261e+00]
 [-2.70807137e-01  9.48501873e-01 -1.21414954e+00 -1.61751433e+00
  -1.35114372e+00]
 [ 1.27410722e+00 -1.00368325e-01  6.96456057e-01 -1.10217376e+00
   8.44822785e-01]
 [-1.19319071e+00 -4.14165203e-01  1.31889356e+00  1.28146617e+00
   1.18480733e+00]]


In [27]:
#23 - Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
#24 - Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
v=np.matmul(np.ones((5,3)),np.ones((3,2)))
print(v)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [29]:
#25 - Given a 1D array, negate all elements which are between 3 and 8, in place
v=np.arange(13)
v[(3<v)&(v<8)]*=-1
print(v)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12]


In [35]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [37]:
#30 - find common values between two arrays?
v1= np.random.randint(0,12,6)
v2= np.random.randint(0,12,6)
print(np.intersect1d(v1,v2))

[ 5 10]


In [ ]:
#33 -  get the dates of yesterday, today and tomorrow?
yesterday= np.datetime64('today') - np.timedelta64(1)
today= np.datetime64('today')
tomorrow= np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2026-02-04 2026-02-05 2026-02-06


In [39]:
#34 - get all the dates corresponding to the month of July 2016?
v= np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(v)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#36 - Extract the integer part of a random array of positive numbers using 4 different methods
v=np.random.uniform(0,10,10)
print(v-v%1)
print(v//1)
print(np.floor(v))
print(v.astype(int))
print(np.trunc(v))

[2. 5. 0. 0. 7. 5. 9. 0. 0. 1.]
[2. 5. 0. 0. 7. 5. 9. 0. 0. 1.]
[2. 5. 0. 0. 7. 5. 9. 0. 0. 1.]
[2 5 0 0 7 5 9 0 0 1]
[2. 5. 0. 0. 7. 5. 9. 0. 0. 1.]


In [ ]:
#37 - 5x5 matrix with row values ranging from 0 to 4 
v=np.zeros((5,5))
v+=np.arange(5)
print(v)
#without broadcasting
b= np.tile(np.arange(0,5),(5,1))
print(b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [44]:
#38 - a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
v=np.fromiter(generate(),dtype=float,count=-1)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#39 - a vector of size 10 with values ranging from 0 to 1, both excluded
v=np.linspace(0,1,11,endpoint=False)[1:]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [46]:
#40 - a random vector of size 10 and sort it
v=np.random.random(10)
v.sort()
print(v)

[0.03227191 0.04182799 0.07290572 0.10210635 0.61112562 0.64410644
 0.81978375 0.8330813  0.8339296  0.95123482]
